/**
 * The error catalog, generated by the compiler.
 *
 * `hard errors --markdown` is the source of truth for every diagnostic: which
 * codes exist, what they mean, and what a bad example looks like. Writing that
 * list by hand would create a second source of truth that drifts from the
 * first, and the failure would be a page telling a reader to look for a code
 * the compiler does not emit.
 *
 * So this script asks the compiler and writes the page. Run it whenever the
 * compiler's diagnostics change, and the content validator will compile the
 * rest of the tree to prove the catalog and the compiler still agree.
 */

import { execFileSync } from "node:child_process";
import { writeFileSync, mkdirSync, existsSync } from "node:fs";
import { join } from "node:path";
import { findCompiler, compilerVersion, REPO_ROOT } from "../src/lib/compiler";

const bin = findCompiler();
if (!bin) {
  console.error("no compiler found: set HARD_BIN or build the compiler in a sibling checkout");
  process.exit(1);
}

let markdown: string;
try {
  markdown = execFileSync(bin, ["errors", "--markdown"], { encoding: "utf8", timeout: 60_000 });
} catch (err) {
  console.error(`\`hard errors --markdown\` failed:\n${(err as Error).message}`);
  process.exit(1);
}

/**
 * MDX is not HTML, and the compiler writes Markdown with two HTML habits MDX
 * rejects: comments, and placeholders like `<name>` used to mean "a field named
 * name". Both are translated here rather than in the catalog, so the compiler
 * keeps emitting plain Markdown and this page stays valid MDX.
 */
function toMdx(source: string): string {
  return source
    .replace(/<!--([\s\S]*?)-->/g, (_, text) => `{/*${text.replace(/\*\//g, "* /")}*/}`)
    // `<name>` is a placeholder, not a tag: backticks say what it means.
    .replace(/<([a-z][a-z0-9_]*)>/gi, (_, tag) => {
      if (tag === "br") return "  ";
      return `\`&lt;${tag}&gt;\``;
    });
}

const codes = [...markdown.matchAll(/^### `(HS\d{4})`/gm)].map((m) => m[1]);
if (codes.length === 0) {
  console.error("the compiler returned a catalog with no codes; refusing to write an empty page");
  process.exit(1);
}

const out = `---
title: Error catalog
description: Every diagnostic the HardScript compiler can emit, with the code, what it means, and a bad example that produces it.
section: Errors
order: 10
template: generated
version: ${process.env.NEXT_PUBLIC_HARD_VERSION ?? "0.9-alpha"}
---

${toMdx(markdown).trim()}

---

*Generated from \`hard errors --markdown\` by \`npm run docs:errors\`, using ${compilerVersion()}.
Do not edit this page by hand — edit the compiler's catalog and regenerate.*
`;

const dir = join(REPO_ROOT, "content", "docs", "errors");
mkdirSync(dir, { recursive: true });
const file = join(dir, "catalog.mdx");
const previous = existsSync(file) ? writeFileSync : null;
void previous;
writeFileSync(file, out, "utf8");
console.log(`errors: wrote ${codes.length} diagnostics to content/docs/errors/catalog.mdx`);
